function fillProductData(){

    var obj = "";
    obj += '<div id="{{product.id}}" className="row mb-5 appear-animation" data-appear-animation="fadeInUpShorter"';
    obj += '     data-appear-animation-delay="750">';
    obj += '    <div className="col">';
    obj += '        <div className="d-flex flex-wrap bg-light box-shadow-4 custom-link-hover-effects">';
    obj += '            <div className="position-relative lazyload col-12 col-md-4"';
    obj += '                 data-bg-src="img/demos/business-consulting-3/team/team-1.jpg"';
    obj += '                 style="background-position: center; background-size: cover; min-height: 320px;">';
    obj += '                <div className="position-absolute bottom-0 left-0 w-100 py-3 px-4 z-index-3">';
    obj += '                   <div className="custom-crooked-line">';
    obj += '                        <img width="154" height="26"';
    obj += '                             src="img/demos/business-consulting-3/icons/infinite-crooked-line.svg" alt="" data-icon';
    obj += '                            data-plugin-options="{\'onlySVG\': true, \'extraClass\': \'svg-fill-color-primary\'}"';
    obj += '                             style="width: 154px;"/>';
    obj += '                    </div>';
    obj += '                </div>';
    obj += '            </div>';
    obj += '            <div className="col-md-8 p-5">';
    obj += '                <div className="d-flex justify-content-between justify-content-md-start mb-4">';
    obj += '                    <div>';
    obj += '                        <h2 className="font-weight-semibold text-6 line-height-1 mb-0">{{product.name}}</h2>';
    obj += '                        <p className="text-3-5 mb-0">{{product.category}}</p>';
    obj += '                    </div>';
    obj += '                    <div className="bg-color-grey ms-4 me-1 d-none d-md-block" style="width: 8px;"></div>';
    obj += '               </div>';
    obj += '                <div className="custom-read-more-style-1" data-plugin-readmore';
    obj += '                    data-plugin-options="{';
    obj += '										\'buttonOpenLabel\': \'View More <i class=\'fas fa-chevron-down text-2 ms-1\'></i>\', ';
        obj += '										\'buttonCloseLabel\': \'View Less <i class=\'fas fa-chevron-up text-2 ms-1\'></i>\',';
    obj += '										\'maxHeight\': 160\'';
    obj += '									}">';
    obj += '                    <p className="text-3-5">{{product.description}}</p>';
    obj += '                    <div className="accordion custom-accordion-style-1 appear-animation"';
    obj += '                         data-appear-animation="fadeInUpShorter" data-appear-animation-delay="250" id="accordion1">';
    obj += '                        <div className="card card-default">';
    obj += '                            <div className="card-header" id="collapse1HeadingOne">';
    obj += '                                <h4 className="card-title m-0">';
    obj += '                                    <a className="accordion-toggle text-color-dark font-weight-bold collapsed"';
    obj += '                                       data-bs-toggle="collapse" data-bs-target="#collapse1One"';
    obj += '                                      aria-expanded="false" aria-controls="collapse1One">';
    obj += '                                        Uses of {{productname}}';
    obj += '                                    </a>';
    obj += '                                </h4>';
    obj += '                            </div>';
    obj += '                           <div id="collapse1One" className="collapse" aria-labelledby="collapse1HeadingOne"';
    obj += '                                 data-bs-parent="#accordion1">';
    obj += '                                <div className="card-body">';
    obj += '                                    <p className="mb-0">{{product.uses}}</p>';
    obj += '                                </div>';
    obj += '                            </div>';
    obj += '                        </div>';
    obj += '                       <div className="card card-default">';
    obj += '                            <div className="card-header" id="collapse1HeadingTwo">';
    obj += '                                <h4 className="card-title m-0">';
    obj += '                                    <a className="accordion-toggle text-color-dark font-weight-bold collapsed"';
    obj += '                                       data-bs-toggle="collapse" data-bs-target="#collapse1Two"';
    obj += '                                       aria-expanded="false" aria-controls="collapse1Two">';
    obj += '                                        Benefits of {{product.name}}';
    obj += '                                    </a>';
    obj += '                                </h4>';
    obj += '                           </div>';
    obj += '                    <div id="collapse1Two" className="collapse" aria-labelledby="collapse1HeadingTwo"';
    obj += '                         data-bs-parent="#accordion1">';
    obj += '                        <div className="card-body">';
    obj += '                            <p className="mb-0">{{product.benefits}}</p>';
    obj += '                        </div>';
    obj += '                    </div>';
    obj += '                </div>';
    obj += '                <div className="card card-default">';
    obj += '                    <div className="card-header" id="collapse1HeadingThree">';
    obj += '                        <h4 className="card-title m-0">';
    obj += '                            <a className="accordion-toggle text-color-dark font-weight-bold collapsed"';
    obj += '                               data-bs-toggle="collapse" data-bs-target="#collapse1Three"';
    obj += '                               aria-expanded="false" aria-controls="collapse1Three">';
    obj += '                                Instruction of using {{product.name}}';
    obj += '                            </a>';
    obj += '                        </h4>';
    obj += '                    </div>';
    obj += '                    <div id="collapse1Three" className="collapse" aria-labelledby="collapse1HeadingThree"';
    obj += '                         data-bs-parent="#accordion1">';
    obj += '                        <div className="card-body">';
    obj += '                            <p className="mb-0">{{product.instructions}}</p>';
    obj += '                        </div>';
    obj += '                    </div>';
    obj += '                </div>';
    obj += '            </div>';
    obj += '            <div className="readmore-button-wrapper d-none">';
    obj += '                <a href="#" className="text-decoration-none">';
    obj += '                    View More';
    obj += '                    <i className="fas fa-chevron-down"></i>';
    obj += '                </a>';
    obj += '            </div>';
    obj += '        </div>';
    obj += '';
    obj += '        </div>';
    obj += '        </div>';
    obj += '    </div>';
    obj += '</div>';
    return obj;
}